// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvMuc_W40_GG75KCSO5nau2LbBXpiBSgE',
    appId: '1:94952939819:web:82a2e66b152b893ba8256e',
    messagingSenderId: '94952939819',
    projectId: 'healthsync-4ca6a',
    authDomain: 'healthsync-4ca6a.firebaseapp.com',
    storageBucket: 'healthsync-4ca6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUbk0bDM_rIUlMceC9ikfhBFasaIzbQgc',
    appId: '1:94952939819:ios:19ecc6e67ab38dd7a8256e',
    messagingSenderId: '94952939819',
    projectId: 'healthsync-4ca6a',
    storageBucket: 'healthsync-4ca6a.appspot.com',
    iosClientId: '94952939819-toa2fi205uj3m4rrumqb5robimsd1r24.apps.googleusercontent.com',
    iosBundleId: 'com.phenotype.healthsync',
  );

}